[theme]
base                     = "light"
primaryColor             = "#d97706"
backgroundColor          = "#fffbf0"
secondaryBackgroundColor = "#fef3c7"
textColor                = "#292524"
font                     = "sans serif"

[server]
headless = true
port     = 8501

[browser]
gatherUsageStats = false
